version: '3'
services:

  shintolin3:
    image: node:carbon
    environment:
      - MONGODB_URI=mongodb://shintolin3-mongo/heroku_8xb5fctf
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["bin/dev/start"]
    ports:
      - "3000:3000"
    depends_on:
      - shintolin3-mongo

  shintolin3-mongo:
    image: mongo
    volumes:
      - .:/host
    ports:
      - "27017:27017"
    logging:
      driver: "none"
